### ISSUE TITLE
https://api.teams.skype.com/beta/auth/skypetoken not reachable anymore

### ISSUE THREAD

**Issue by bk-td** [sanderdewit/intune-module#1]
Hi Sander,

Sorry this issue is related to your other repository teams module, but as that's archived, I try my chances and post it here.

The https://api.teams.skype.com/beta/auth/skypetoken is no longer available, do you know if there is another way or url to retrieve the skypetoken from?

Thansk

**Comment by sanderdewit** [comment]
oh wow this is a very overdue response, but somehow I completely missed this message, apologies.
The reason the teams-module is archived is because Microsoft has released a PowerShell module to configure Teams.

**Comment by sanderdewit** [comment]
try https://api.userstore.skype.com

**Comment by sanderdewit** [comment]
Created a request with the following properties: {"LoginHint":"<USERUPN>","msafed":"1","correlationId":">{ID}","resource":"https://api.spaces.skype.com","claims":"{\"access_token\":{\"xms_cc\":{\"values\":[\"CP1\"]}}}"}

**Comment by bk-td** [comment]
Thanks for taking the time to reply.
I'll give it a try.
